### ISSUE TITLE
support more service brokers for the microsoft sql server connector

### ISSUE THREAD

**Issue by bingosummer** [SteeltoeOSS/Connectors#20]
From https://steeltoe.io/docs/steeltoe-connectors/#3-0-microsoft-sql-server, it seems that only the [Microsoft SQL Server broker](https://github.com/cloudfoundry-incubator/mssql-server-broker) is supported.
Is it possible to support other service broker which also provides Microsoft SQL service? For example, https://github.com/Azure/open-service-broker-azure.
If not supported, what should be done to support it? A new provider connector similar to https://github.com/SteeltoeOSS/Connectors/tree/dev/src/Steeltoe.CloudFoundry.ConnectorBase/Relational/SqlServer ?

**Comment by TimHess** [comment]
Ideally, that broker would work as well. The reason it isn't currently supported is that (as I understand it) the Azure Open Service Broker does something with URL Encoding that the other broker doesn't do. We do have a ticket logged on our Tracker backlog here https://www.pivotaltracker.com/story/show/157010231 but I haven't had a chance to look at it yet

**Comment by TimHess** [comment]
Steeltoe should work with PostgreSQL, MySQL, Azure SQL and Redis services provisioned by the Azure Open Service Broker as of version 2.1.1 (released today)
