### ISSUE TITLE
Create a health check for MongoDB

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Connectors#27]
We now have a MongoDB connector so should also have a health check (HealthContributor).

**Comment by TimHess** [comment]
If we can't add compatibility with Microsoft's new health checks or BeatPulse, perform the same check  [BeatPulse is doing](https://github.com/Xabaril/BeatPulse/blob/master/src/BeatPulse.MongoDb/MongoDbLiveness.cs)
