### ISSUE TITLE
Addition of multiplexer uses sealed type not interface

### ISSUE THREAD

**Issue by autodidaddict** [SteeltoeOSS/Connectors#3]
When you call `AddRedisConnectionMultiplexer`, it registers the service by binding a singleton of type `ConnectionMultiplexer`. This means that any class that was properly written for testing against the `IConnectionMultiplexer` interface (which `ConnectionMultiplexer` implements) will fail to get an instance from the services provider.

Please change 
```
services.AddSingleton(typeof(ConnectionMultiplexer), factory.CreateConnection);
```

to 
```
services.AddSingleton(typeof(IConnectionMultiplexer), factory.CreateConnection);
```

**Comment by dtillman** [comment]
Thanks,
Made the change!
