### ISSUE TITLE
Connector Binding to CUPS

### ISSUE THREAD

**Issue by pnguyen535** [SteeltoeOSS/Connectors#48]
Currently, I have multiple CUPS on my services. However, I could not get the EF Core Binding to work with CUPS. The example below is generated by Cloud Foundry when I use CUPS.

"system_env_json": {
    "VCAP_SERVICES": {
      "user-provided": [
        {
          "name": "cups-1",
          "instance_name": "cups-1",
          "binding_name": null,
          "credentials": {
            "uri": "jdbc:sqlserver:soemthing",
            "uid": "",
            "pw": ""
          },
          "syslog_drain_url": "",
          "volume_mounts": [],
          "label": "user-provided",
          "tags": []
        },
        {
          "name": "cups-2",
          "instance_name": "cups-2",
          "binding_name": null,
          "credentials": {},
          "syslog_drain_url": "",
          "volume_mounts": [],
          "label": "user-provided",
          "tags": []
        }
      ]
    }
  }

**Comment by TimHess** [comment]
If the uri is as you have it in this issue: `jdbc:sqlserver:something` and not `jdbc:sqlserver://something` that could explain it.

There are several formats that should work, this file shows a few of them https://github.com/SteeltoeOSS/Connectors/blob/dev/test/Steeltoe.CloudFoundry.ConnectorCore.Test/SqlServerTestHelpers.cs

**Comment by pnguyen535** [comment]
Hi Tim,
The issue is that I don't use Data Store provided by Cloud Foundry. I am using the external data store, which is tunneling through Customer User Provided Service. As you can see from the example, it doesn't match with anything thing provided by Steeltoe.

Thank you

**Comment by pnguyen535** [comment]
Hi Tim,

I think something wrong with the way I setup the connection data. This is the normal way to setup for .net, but I don't how to setup for Steeltoe. Please help

Data Source=A5778920.mydomain.com\SQL_ETC_EMT_01;Initial Catalog=ETM_Common;uid=me;pw=me;

thank you

**Comment by TimHess** [comment]
Hi @pnguyen535,

I think the reason it wasn't working for you is that named instances weren't well supported with the SQL Connector. With the latest changes I just made, you should be able to connect with this style of uri:

```json
"credentials": {
    "uri": "sqlserver://username:password@A5778920.mydomain.com/ETM_Common;instanceName=SQL_ETC_EMT_01",
}
```

Are you able to pull the latest package from the dev feed to try it out?

**Comment by jkonicki** [comment]
Closing this issue.  If need reopened, please open under `steeltoe` repository.
