### ISSUE TITLE
RabbitConnector not picking up SSL settings

### ISSUE THREAD

**Issue by jquintero33** [SteeltoeOSS/Connectors#5]
When running my app on PCF the rabbit ConnectionFactory object is being initialized with the port set to 5672 instead of 5671 as is set in the app's environment variables under VCAP_SERVICES:p-rabbitmq:credentials:amqp+ssl:port. In addition, the Ssl property is not initalized. The hostname, username, and password are all picked up correctly however. Can you confirm if the connector supports Rabbit instances requiring SSL?

**Comment by dtillman** [comment]
@jquintero33 : Can you paste in the VCAP_SERVICES environment variables you see for the app.  Also, what version of Rabbit Tile are you running with?

Dave

**Comment by jquintero33** [comment]
"p-rabbitmq": [
        {
          "credentials": {
            "http_api_uris": [
              "https://username:pass@my.hostname.io/api/"
            ],
            "ssl": true,
            "dashboard_url": "https://my.hostname.io/#/login/username/password",
            "password": "password",
            "protocols": {
              "management+ssl": {
                "path": "/api/",
                "ssl": false,
                "hosts": [
                  "my.hostname.io"
                ],
                "password": "password",
                "username": "username",
                "port": 15672,
                "host": "my.hostname.io",
                "uri": "http://username:password@my.hostname.io:15672/api/",
                "uris": [
                  "http://username:password@my.hostname.io:15672/api/"
                ]
              },
              "amqp+ssl": {
                "vhost": "16efdc82-2feb-424c-91a3-9f16b95665c7",
                "username": "username",
                "password": "password",
                "port": 5671,
                "host": "my.hostname.io",
                "hosts": [
                  "my.hostname.io"
                ],
                "ssl": true,
                "uri": "amqps://username:password@my.hostname.io:5671/16efdc82-2feb-424c-91a3-9f16b95665c7",
                "uris": [
                  "amqps://username:password@my.hostname.io:5671/16efdc82-2feb-424c-91a3-9f16b95665c7"
                ]
              }
            },
            "username": "username",
            "hostname": "my.hostname.io",
            "hostnames": [
              "my.hostname.io"
            ],
            "vhost": "16efdc82-2feb-424c-91a3-9f16b95665c7",
            "http_api_uri": "https://username:password@rabbit.my.hostname.io/api/",
            "uri": "amqps://username:password@my.hostname.io/16efdc82-2feb-424c-91a3-9f16b95665c7",
            "uris": [
              "amqps://username:password@my.hostname.io/16efdc82-2feb-424c-91a3-9f16b95665c7"
            ]
          },
          "syslog_drain_url": null,
          "volume_mounts": [],
          "label": "p-rabbitmq",
          "provider": null,
          "plan": "standard",
          "name": "test-rabbitmq",
          "tags": [
            "rabbitmq",
            "messaging",
            "message-queue",
            "amqp",
            "stomp",
            "mqtt",
            "pivotal"
          ]
        }
      ]

We are running 3.6.5.

Thanks

**Comment by dtillman** [comment]
@jquintero33: Thanks ... I'll take a look at the SSL support.
Dave

**Comment by dtillman** [comment]
@jquintero33 : Ya... the connector currently doesn't support/work with SSL properly...
I'll fix... and try to get the fix into the 1.0.1 release I'm preparing.
Thanks for reporting.
Dave

**Comment by dtillman** [comment]
@jquintero33 : 

Ok, I've fixed the Rabbit connector... it should now work with SSL bindings.

If you want to test it out... you can reference version 1.0.1-dev-00107 of the connector. This NuGet is on the Steeltoe Development Feed: http://myget.org/feed/steeltoedev/package/nuget/Steeltoe.CloudFoundry.Connector.Rabbit

I'll add the fix to the 1.0.1 release when its built.

Dave
