### ISSUE TITLE
Add option to append "Persist Security Info=true" to MySql connector

### ISSUE THREAD

**Issue by jquintero33** [SteeltoeOSS/Connectors#7]
The ConnectionString property of the connection object returned from the MySql connector does not include the password since the "Persist Security Info=true" option is not included in the connection string used to construct the connection. Since I would like to instantiate the connection objects myself I was hoping to be able to just grab the connection string from the connection object returned from the connector. Can an option be added so "Persist Security Info=true" can be included in the connection string?

**Comment by dtillman** [comment]
@jquintero33 : 
I'll take a look at this for an upcoming release.
Dave

**Comment by TimHess** [comment]
This option is part of the 2.0 release
