### ISSUE TITLE
Make RedisServiceConnectorFactory retrieval reusable

### ISSUE THREAD

**Issue by tillig** [SteeltoeOSS/Connectors#9]
In [`RedisCacheServiceCollectionExtensions`](https://github.com/SteeltoeOSS/Connectors/blob/master/src/Steeltoe.CloudFoundry.Connector.Redis/RedisCacheServiceCollectionExtensions.cs) all of the extension methods repeat this same little block of code to get a populated `RedisServiceConnectorFactory`:

```csharp
RedisCacheConnectorOptions redisConfig = new RedisCacheConnectorOptions(config);
RedisServiceInfo info = config.GetSingletonServiceInfo<RedisServiceInfo>();
RedisServiceConnectorFactory factory = new RedisServiceConnectorFactory(info, redisConfig);
```

In a recent project I was trying to use Redis as a backing store for configuration and wanted to use the nicely built connection parsing to set that up. Unfortunately, all of that happens before DI is started, so just adding an `IDistributedCache` or whatever to the service collection doesn't help.

Could there be a new reusable extension like this added? (I can PR it if so...)

```csharp
public static RedisServiceConnectorFactory CreateRedisServiceConnectorFactory(this IConfiguration config)
{
  if (config == null)
  {
    throw new ArgumentNullException(nameof(config));
  }

  RedisCacheConnectorOptions redisConfig = new RedisCacheConnectorOptions(config);
  RedisServiceInfo info = config.GetSingletonServiceInfo<RedisServiceInfo>();
  return new RedisServiceConnectorFactory(info, redisConfig);
}
```

**Comment by dtillman** [comment]
@tillig 

A PR or other contributions are always welcome!

Dave

**Comment by dtillman** [comment]
Thanks @tillig,
I'll start looking at and merging your contributions into the 2.0 development line that I'm about to start on... ... I want to refactor several of the Steeltoe frameworks in that time frame... and many of your contributions (i.e in other repos as well) are spot on....

Dave
